"""Scaffolder for new common-keywords.

Generates `.resource` (default) or Python `@keyword` (`--python`) keyword
files under ``src/robot_common_keywords/`` plus a self-test stub, and
appends a placeholder row to docs/COVERAGE.md.

See PROJECT_CONTEXT.md §5.2 for the manual checklist that follows the
scaffold.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Sequence

PACKAGE_ROOT = Path("src") / "robot_common_keywords"


_RESOURCE_TEMPLATE = """\
*** Settings ***
Documentation    {name}. TODO(new_keyword.py): one-line summary of what
...              this keyword validates.
...              Generated by scripts/new_keyword.py for {domain}/{module}.resource.
Library          Browser
Resource         _helpers.resource


*** Keywords ***
{name}
    [Documentation]    TODO(new_keyword.py): describe what is checked.
    ...                When composing multiple checks, list them in a
    ...                numbered sequence.
    ...
    ...                Arguments:
    ...                - ``field_locator``  — Playwright selector of the input.
    ...                - ``error_message``  — substring of the visible error text.
    ...                - ``error_locator``  — optional selector for the error element.
    ...                - ``trigger``        — ``blur`` (default) or ``submit``.
    ...                - ``submit_locator`` — required when ``trigger=submit``.
    [Arguments]    ${{field_locator}}
    ...            ${{error_message}}=TODO(new_keyword.py): default error text
    ...            ${{error_locator}}=${{EMPTY}}
    ...            ${{trigger}}=blur
    ...            ${{submit_locator}}=${{EMPTY}}

    # TODO(new_keyword.py): replace this body with the validation steps.
    Fill Text    ${{field_locator}}    ${{EMPTY}}
    Trigger Field Validation    ${{field_locator}}    ${{trigger}}    ${{submit_locator}}
    Validation Error Should Be Visible
    ...    error_message=${{error_message}}
    ...    error_locator=${{error_locator}}
"""


_SELF_TEST_TEMPLATE = """\
*** Settings ***
Documentation    Self-test for {name}. TODO(new_keyword.py): describe
...              the fixture interaction this exercises.
Library          Browser
Resource         robot_common_keywords/{domain}/{module}.resource
Suite Setup      Set Up Browser
Suite Teardown   Close Browser    ALL
Test Setup       Go To    ${{FIXTURE_URL}}
Test Teardown    Run Keyword If Test Failed    Take Screenshot    fullPage=${{True}}


*** Variables ***
${{BROWSER}}        chromium
${{HEADLESS}}       ${{True}}
${{FIXTURE_URL}}    file://${{CURDIR}}/fixtures/text_form.html


*** Test Cases ***
{name} Smoke
    [Tags]    todo    {domain}
    # TODO(new_keyword.py): call {name} with a fixture-appropriate selector.
    Fail    TODO(new_keyword.py): replace this stub with a real assertion.


*** Keywords ***
Set Up Browser
    New Browser    browser=${{BROWSER}}    headless=${{HEADLESS}}
    New Context
    New Page
"""


def render_resource(name: str, module: str, domain: str) -> str:
    """Return the body of a new <domain>/<module>.resource file."""
    return _RESOURCE_TEMPLATE.format(name=name, module=module, domain=domain)


def render_self_test(name: str, module: str, domain: str) -> str:
    """Return the body of a new tests/test_<module>.robot self-test stub."""
    return _SELF_TEST_TEMPLATE.format(name=name, module=module, domain=domain)


_PYTHON_LIBRARY_TEMPLATE = '''\
"""TODO(new_keyword.py): one-line module description."""

from __future__ import annotations

from robot.api.deco import keyword

ROBOT_LIBRARY_SCOPE = "GLOBAL"


@keyword("{name}")
def {func_name}() -> None:
    """TODO(new_keyword.py): describe what this keyword returns or does.

    Predicate keywords (``Is X``, ``Has X``) should return ``False`` on
    bad input rather than raising. Imperative keywords (``Format X``,
    ``Compute X``) may raise; let the underlying library exception
    propagate rather than swallowing it.
    """
    raise NotImplementedError("TODO(new_keyword.py)")
'''


def keyword_to_function_name(name: str) -> str:
    """Convert a Title Case keyword name to a snake_case function name."""
    return "_".join(token.lower() for token in name.split())


def render_python_library(name: str, module: str) -> str:
    """Return the body of a new libraries/<module>.py file."""
    return _PYTHON_LIBRARY_TEMPLATE.format(
        name=name,
        module=module,
        func_name=keyword_to_function_name(name),
    )


def coverage_row(name: str, module: str) -> str:
    """Return a single Markdown table row to append to docs/COVERAGE.md."""
    return f"| `{name}` | `test_{module}.robot` (TODO) | TODO |\n"


def append_coverage_row(coverage_path: Path, name: str, module: str) -> None:
    """Append a placeholder row to the given COVERAGE.md path.

    Idempotent only via filesystem state — call sites are responsible for
    not double-invoking. The scaffolder's overwrite check (Task 6)
    guards against re-running on the same module.
    """
    row = coverage_row(name=name, module=module)
    with coverage_path.open("a", encoding="utf-8") as fp:
        fp.write(row)


_DOMAINS = ("form_validation", "api_validation", "ui_validation", "data_generators")


def _checklist(domain: str, module: str, python_mode: bool) -> str:
    """Return the manual checklist printed after a successful scaffold."""
    if python_mode:
        return (
            f"\nScaffolded src/robot_common_keywords/libraries/{module}.py.\n"
            "Next steps:\n"
            "  1. Replace TODO(new_keyword.py) markers with real implementation.\n"
            "  2. Add coverage in the consuming .resource file's self-test\n"
            "     (Python @keyword libraries are tested transitively).\n"
            "  3. Update docs/COVERAGE.md row with the actual self-test name.\n"
            "  4. Regenerate libdoc: ./scripts/generate-keyword-catalog.sh\n"
        )
    return (
        f"\nScaffolded src/robot_common_keywords/{domain}/{module}.resource "
        f"and tests/test_{module}.robot.\n"
        "Next steps:\n"
        "  1. Replace TODO(new_keyword.py) markers in Documentation, Arguments, body.\n"
        "  2. Add YAML test data under src/robot_common_keywords/test_data/ if needed.\n"
        f"  3. Run dryrun from repo root after pip install -e .: "
        f"robot --dryrun tests/test_{module}.robot\n"
        "  4. Implement the keyword body until the self-test passes.\n"
        f"  5. Run full suite: robot -d results --exclude network tests/\n"
        "  6. Regenerate libdoc: ./scripts/generate-keyword-catalog.sh\n"
        "  7. Update docs/COVERAGE.md row with the actual self-test name.\n"
    )


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Scaffold a new common-keyword (.resource by default, "
                    "or Python @keyword library with --python).",
    )
    parser.add_argument("--domain", required=True, choices=_DOMAINS)
    parser.add_argument("--name", required=True,
                        help='Title-Case keyword name, e.g. "Validate Postal Code Field"')
    parser.add_argument("--module", required=True,
                        help="snake_case basename (no extension), e.g. postal_code_field")
    parser.add_argument("--python", action="store_true",
                        help="Generate a Python @keyword library under libraries/ "
                             "instead of a .resource file.")
    args = parser.parse_args(argv)

    cwd = Path.cwd()
    coverage_path = cwd / "docs" / "COVERAGE.md"

    if args.python:
        target = cwd / PACKAGE_ROOT / "libraries" / f"{args.module}.py"
        if target.exists():
            print(f"error: {target} already exists; refusing to overwrite.",
                  file=sys.stderr)
            return 1
        target.write_text(render_python_library(name=args.name, module=args.module), encoding="utf-8")
    else:
        resource = cwd / PACKAGE_ROOT / args.domain / f"{args.module}.resource"
        self_test = cwd / "tests" / f"test_{args.module}.robot"
        if resource.exists() or self_test.exists():
            print(f"error: {resource} or {self_test} already exists; "
                  "refusing to overwrite.", file=sys.stderr)
            return 1
        resource.write_text(render_resource(
            name=args.name, module=args.module, domain=args.domain), encoding="utf-8")
        self_test.write_text(render_self_test(
            name=args.name, module=args.module, domain=args.domain), encoding="utf-8")

    if coverage_path.exists():
        append_coverage_row(coverage_path=coverage_path,
                            name=args.name, module=args.module)

    print(_checklist(domain=args.domain, module=args.module,
                     python_mode=args.python))
    return 0


if __name__ == "__main__":
    sys.exit(main())
