"""Scaffolder for new common-keywords.

Generates `.resource` (default) or Python `@keyword` (`--python`) keyword
files plus a self-test stub, and appends a placeholder row to
docs/COVERAGE.md.

See PROJECT_CONTEXT.md §5.2 for the manual checklist that follows the
scaffold.
"""

from __future__ import annotations

from pathlib import Path


_RESOURCE_TEMPLATE = """\
*** Settings ***
Documentation    {name}. TODO(new_keyword.py): one-line summary of what
...              this keyword validates.
...              Generated by scripts/new_keyword.py for {domain}/{module}.resource.
Library          Browser
Resource         _helpers.resource


*** Keywords ***
{name}
    [Documentation]    TODO(new_keyword.py): describe what is checked.
    ...                When composing multiple checks, list them in a
    ...                numbered sequence.
    ...
    ...                Arguments:
    ...                - ``field_locator``  — Playwright selector of the input.
    ...                - ``error_message``  — substring of the visible error text.
    ...                - ``error_locator``  — optional selector for the error element.
    ...                - ``trigger``        — ``blur`` (default) or ``submit``.
    ...                - ``submit_locator`` — required when ``trigger=submit``.
    [Arguments]    ${{field_locator}}
    ...            ${{error_message}}=TODO(new_keyword.py): default error text
    ...            ${{error_locator}}=${{EMPTY}}
    ...            ${{trigger}}=blur
    ...            ${{submit_locator}}=${{EMPTY}}

    # TODO(new_keyword.py): replace this body with the validation steps.
    Fill Text    ${{field_locator}}    ${{EMPTY}}
    Trigger Field Validation    ${{field_locator}}    ${{trigger}}    ${{submit_locator}}
    Validation Error Should Be Visible
    ...    error_message=${{error_message}}
    ...    error_locator=${{error_locator}}
"""


_SELF_TEST_TEMPLATE = """\
*** Settings ***
Documentation    Self-test for {name}. TODO(new_keyword.py): describe
...              the fixture interaction this exercises.
Library          Browser
Resource         ../{domain}/{module}.resource
Suite Setup      Set Up Browser
Suite Teardown   Close Browser    ALL
Test Setup       Go To    ${{FIXTURE_URL}}
Test Teardown    Run Keyword If Test Failed    Take Screenshot    fullPage=${{True}}


*** Variables ***
${{BROWSER}}        chromium
${{HEADLESS}}       ${{True}}
${{FIXTURE_URL}}    file://${{CURDIR}}/fixtures/text_form.html


*** Test Cases ***
{name} Smoke
    [Tags]    todo    {domain}
    # TODO(new_keyword.py): call {name} with a fixture-appropriate selector.
    Fail    TODO(new_keyword.py): replace this stub with a real assertion.


*** Keywords ***
Set Up Browser
    New Browser    browser=${{BROWSER}}    headless=${{HEADLESS}}
    New Context
    New Page
"""


def render_resource(name: str, module: str, domain: str) -> str:
    """Return the body of a new <domain>/<module>.resource file."""
    return _RESOURCE_TEMPLATE.format(name=name, module=module, domain=domain)


def render_self_test(name: str, module: str, domain: str) -> str:
    """Return the body of a new tests/test_<module>.robot self-test stub."""
    return _SELF_TEST_TEMPLATE.format(name=name, module=module, domain=domain)


_PYTHON_LIBRARY_TEMPLATE = '''\
"""TODO(new_keyword.py): one-line module description."""

from __future__ import annotations

from robot.api.deco import keyword

ROBOT_LIBRARY_SCOPE = "GLOBAL"


@keyword("{name}")
def {func_name}() -> None:
    """TODO(new_keyword.py): describe what this keyword returns or does.

    Predicate keywords (``Is X``, ``Has X``) should return ``False`` on
    bad input rather than raising. Imperative keywords (``Format X``,
    ``Compute X``) may raise; let the underlying library exception
    propagate rather than swallowing it.
    """
    raise NotImplementedError("TODO(new_keyword.py)")
'''


def keyword_to_function_name(name: str) -> str:
    """Convert a Title Case keyword name to a snake_case function name."""
    return "_".join(token.lower() for token in name.split())


def render_python_library(name: str, module: str) -> str:
    """Return the body of a new libraries/<module>.py file."""
    return _PYTHON_LIBRARY_TEMPLATE.format(
        name=name,
        module=module,
        func_name=keyword_to_function_name(name),
    )


def coverage_row(name: str, module: str) -> str:
    """Return a single Markdown table row to append to docs/COVERAGE.md."""
    return f"| `{name}` | `test_{module}.robot` (TODO) | TODO |\n"


def append_coverage_row(coverage_path: Path, name: str, module: str) -> None:
    """Append a placeholder row to the given COVERAGE.md path.

    Idempotent only via filesystem state — call sites are responsible for
    not double-invoking. The scaffolder's overwrite check (Task 6)
    guards against re-running on the same module.
    """
    row = coverage_row(name=name, module=module)
    with coverage_path.open("a", encoding="utf-8") as fp:
        fp.write(row)
