"""Scaffolder for new common-keywords.

Generates `.resource` (default) or Python `@keyword` (`--python`) keyword
files plus a self-test stub, and appends a placeholder row to
docs/COVERAGE.md.

See PROJECT_CONTEXT.md §5.2 for the manual checklist that follows the
scaffold.
"""

from __future__ import annotations


_RESOURCE_TEMPLATE = """\
*** Settings ***
Documentation    {name}. TODO(new_keyword.py): one-line summary of what
...              this keyword validates.
...              Generated by scripts/new_keyword.py for {domain}/{module}.resource.
Library          Browser
Resource         _helpers.resource


*** Keywords ***
{name}
    [Documentation]    TODO(new_keyword.py): describe what is checked.
    ...                When composing multiple checks, list them in a
    ...                numbered sequence.
    ...
    ...                Arguments:
    ...                - ``field_locator``  — Playwright selector of the input.
    ...                - ``error_message``  — substring of the visible error text.
    ...                - ``error_locator``  — optional selector for the error element.
    ...                - ``trigger``        — ``blur`` (default) or ``submit``.
    ...                - ``submit_locator`` — required when ``trigger=submit``.
    [Arguments]    ${{field_locator}}
    ...            ${{error_message}}=TODO(new_keyword.py): default error text
    ...            ${{error_locator}}=${{EMPTY}}
    ...            ${{trigger}}=blur
    ...            ${{submit_locator}}=${{EMPTY}}

    # TODO(new_keyword.py): replace this body with the validation steps.
    Fill Text    ${{field_locator}}    ${{EMPTY}}
    Trigger Field Validation    ${{field_locator}}    ${{trigger}}    ${{submit_locator}}
    Validation Error Should Be Visible
    ...    error_message=${{error_message}}
    ...    error_locator=${{error_locator}}
"""


_SELF_TEST_TEMPLATE = """\
*** Settings ***
Documentation    Self-test for {name}. TODO(new_keyword.py): describe
...              the fixture interaction this exercises.
Library          Browser
Resource         ../{domain}/{module}.resource
Suite Setup      Set Up Browser
Suite Teardown   Close Browser    ALL
Test Setup       Go To    ${{FIXTURE_URL}}
Test Teardown    Run Keyword If Test Failed    Take Screenshot    fullPage=${{True}}


*** Variables ***
${{BROWSER}}        chromium
${{HEADLESS}}       ${{True}}
${{FIXTURE_URL}}    file://${{CURDIR}}/fixtures/text_form.html


*** Test Cases ***
{name} Smoke
    [Tags]    todo    {domain}
    # TODO(new_keyword.py): call {name} with a fixture-appropriate selector.
    Fail    TODO(new_keyword.py): replace this stub with a real assertion.


*** Keywords ***
Set Up Browser
    New Browser    browser=${{BROWSER}}    headless=${{HEADLESS}}
    New Context
    New Page
"""


def render_resource(name: str, module: str, domain: str) -> str:
    """Return the body of a new <domain>/<module>.resource file."""
    return _RESOURCE_TEMPLATE.format(name=name, module=module, domain=domain)


def render_self_test(name: str, module: str, domain: str) -> str:
    """Return the body of a new tests/test_<module>.robot self-test stub."""
    return _SELF_TEST_TEMPLATE.format(name=name, module=module, domain=domain)
